### ISSUE TITLE
Incorrect path value added with Windows installer

### ISSUE THREAD

**Issue by brian36** [sbt/sbt-launcher-package#76]
I installed sbt 0.13.6 through the windows msi installer on WIndows 7.

However, after installing and opening a command prompt, "sbt sbt-version" resulted in the regular statement that the command wasn't recongized.

I checked the "Path" environment variable and `"C:\Program Files (x86)\sbt\\bin"` had been added instead of `"C:\Program Files (x86)\sbt\bin"`.  I removed the extra backslash and that fixed it.

**Comment by AlixBa** [comment]
Confirming this again. Just installed sbt 0.13.9 and the path was set to `C:\Program Files (x86)\sbt\\bin`

**Comment by eed3si9n** [comment]
Dale (@dwijnand) fixed the issue in #110 so I published a new installer for Windows for 0.13.12. Could you try using it, and see if it fixes the issue for you?
http://www.scala-sbt.org/download.html

**Comment by Pereitor** [comment]
Just downloaded and installed it using SBT-0.13.12.MSI. Still happening.
Can't believe a bug of this kind opened in 2014 still exists more than two years after being opened in what's so-called a "professional" tool. 
Not the first nor the second problem of this kind with Scala / Play 2 Framework. Very discouraging.

**Comment by eed3si9n** [comment]
@Pereitor could you try the latest? http://dl.bintray.com/sbt/native-packages/sbt/0.13.13.1/:sbt-0.13.13.1.msi
